export type { CourseClass, FetchClasses, LearningClass } from './class'
export type { SelectItems } from './selectItems'
export type { TimeLesson } from './timeLesson'
export type { FetchError } from './fetchError'
export type { DateLastUpdate } from './date'